<?php

declare(strict_types=1);

namespace Amid\Sms\Otp;

use Amid\Sms\Contracts\OtpCodeGenerator;
use Amid\Sms\Contracts\PhoneNormalizer;
use Amid\Sms\Enums\MessageStatus;
use Amid\Sms\Exceptions\InvalidRecipient;
use Amid\Sms\Exceptions\SmsException;
use Amid\Sms\SmsManager;
use Illuminate\Contracts\Cache\Repository;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Hash;

/**
 * One-time codes, generated and verified **by this package**.
 *
 * ⚠️ **The provider only delivers.** Several Iranian providers offer to generate a
 * code themselves and hand it back, and this package deliberately does not use
 * that: a code that exists only inside provider A cannot be delivered by provider
 * B when provider A is down. Owning the code is what makes an OTP failover across
 * gateways the same way any other message does — the proof is in the tests, where
 * one generated code reaches two different providers unchanged.
 *
 * It is built entirely on the ordinary send pipeline. There is no OTP gateway, no
 * `sms.otp_driver`, no OTP-specific driver method. An OTP template is a template,
 * bound to gateways the ordinary way, routed by capability and country, failed
 * over by the ordinary rules, and recorded in the ordinary tables.
 *
 * ⚠️ **Every OTP send is forced sensitive**, whatever the template says. Security
 * that depends on somebody remembering to tick a box is not security; see send().
 *
 * What it owns, and nothing more: generating the code, storing a hash of it,
 * counting failed guesses, the resend cooldown, and saying yes or no to a guess.
 * There are no routes, no controllers, no middleware and no notion of a user —
 * when to challenge somebody is the application's decision.
 */
final class OtpManager
{
    /**
     * The logical variable the code is supplied as.
     *
     * ⚠️ A LOGICAL name, not a provider parameter. Each gateway's `parameter_map`
     * translates it into whatever that provider calls it — Kavenegar's `token`,
     * SMS.ir's registered name, IPPanel's `otp` — exactly as for any other
     * variable. The OTP API never mentions a provider's vocabulary.
     */
    public const VARIABLE = 'code';

    public function __construct(
        private readonly SmsManager $sms,
        private readonly PhoneNormalizer $normalizer,
        private readonly OtpCodeGenerator $generator,
    ) {}

    /**
     * Generate a code, store its hash, and send it.
     *
     * ⚠️ Synchronous, deliberately. A code is worth ninety seconds and the person
     * is looking at the screen; a queued send trades that for a background worker
     * that may deliver it after it has expired. Immediate multi-gateway failover
     * already provides the availability a queue would have been for.
     *
     * @param  array<string, string|int|float|null>  $variables  additional logical
     *                                                           variables the wording needs
     * @param  string|null  $purpose  defaults to the template key
     *
     * @throws InvalidRecipient  the number is not sendable
     * @throws SmsException      the caller tried to supply the code itself
     */
    public function send(string $to, string $template, array $variables = [], ?string $purpose = null): OtpResult
    {
        if (array_key_exists(self::VARIABLE, $variables)) {
            /*
             * ⚠️ Refused, not overwritten silently.
             *
             * A caller passing `code` either believes it is choosing the one-time
             * code — which would make it guessable by whatever chose it — or has a
             * name collision that would put its own value where the code belongs
             * and send a working-looking message containing no code at all. Both
             * are bugs, and both are invisible if this quietly wins.
             */
            throw new SmsException(sprintf(
                'The [%s] variable is generated by this package and cannot be supplied by the caller.',
                self::VARIABLE,
            ));
        }

        $number = $this->normalizer->normalize($to) ?? throw InvalidRecipient::for($to);
        $purpose ??= $template;
        $config = $this->config();

        $lock = $this->cache()->lock($this->key('lock', $number->e164, $purpose), 10);

        if (! $lock->get()) {
            // Somebody else is mid-send for this number and purpose. Two concurrent
            // requests must not produce two codes, and the loser is told the same
            // thing the cooldown tells everyone.
            return OtpResult::cooldown($config['resend_after']);
        }

        try {
            /*
             * ⚠️ The cooldown is claimed BEFORE a code is generated, with an atomic
             * add. `add()` writes only if the key is absent and reports whether it
             * did, so two callers racing here cannot both proceed even without the
             * lock above. Generating first and checking after would mint a code
             * nobody could ever receive.
             */
            if (! $this->cache()->add($this->key('cooldown', $number->e164, $purpose), 1, $config['resend_after'])) {
                return OtpResult::cooldown($config['resend_after']);
            }

            $code = $this->generator->generate($config['length']);

            /*
             * ⚠️ Stored before the send, not after.
             *
             * A provider can deliver an SMS faster than this process finishes its
             * own request. Storing afterwards leaves a window in which somebody is
             * looking at a code that this package does not yet believe exists.
             *
             * Writing it replaces any surviving challenge, so a resend invalidates
             * the previous code the moment the new one is issued — there is never
             * more than one live code per number and purpose.
             */
            $this->write($number->e164, $purpose, $code, $config);

            $message = $this->sms->to($number->e164)
                ->template($template)
                ->with([...$variables, self::VARIABLE => $code])
                // ⚠️ Forced, regardless of the template's own flag. See the class
                // comment: this is the line that makes OTP safety independent of
                // how carefully somebody configured a row.
                ->sensitive()
                ->send();

            return $this->settle($message, $number->e164, $purpose);
        } finally {
            $lock->release();
        }
    }

    /**
     * Check a code somebody typed.
     *
     * Returns a plain boolean, deliberately. "Wrong code", "expired", "too many
     * attempts" and "no challenge at all" are four different facts and telling a
     * caller which one applies tells an attacker which one applies — including
     * whether this number was ever challenged. The application shows one message.
     *
     * ⚠️ The purpose is REQUIRED, and was made so before the first release. It
     * used to be nullable "defaulting to the template key" - except nothing
     * defaulted: a null purpose simply returned false, so `verify($to, $code)`
     * silently rejected every correct code. A parameter whose omission makes a
     * security check always fail is a trap, and the honest signature is the one
     * that will not compile without the answer. Pass what you sent with; `send()`
     * uses the template key when you give it no purpose of your own.
     *
     * @param  string  $purpose  the same purpose the code was sent under
     */
    public function verify(string $to, string $code, string $purpose): bool
    {
        $number = $this->normalizer->normalize($to);

        if ($number === null || trim($code) === '') {
            return false;
        }

        $lock = $this->cache()->lock($this->key('lock', $number->e164, $purpose), 10);

        if (! $lock->get()) {
            /*
             * ⚠️ A refusal, not a wait.
             *
             * Only one verification of a challenge may ever succeed, so two
             * simultaneous attempts with the correct code must not both consume it.
             * The one that loses the lock is refused; the person tries again a
             * second later, by which point the challenge is either gone (they
             * succeeded) or still there.
             */
            return false;
        }

        try {
            $key = $this->key('challenge', $number->e164, $purpose);
            $challenge = $this->cache()->get($key);

            if (! is_array($challenge) || ! isset($challenge['hash'], $challenge['attempts'], $challenge['expires_at'])) {
                // Expired, consumed, or never existed. All the same answer.
                return false;
            }

            $config = $this->config();

            if ((int) $challenge['attempts'] >= $config['max_attempts']) {
                // Budget already spent. A correct code after that is still wrong,
                // which is the whole point of an attempt limit.
                $this->cache()->forget($key);

                return false;
            }

            if (Hash::check($code, (string) $challenge['hash'])) {
                // ⚠️ Single use. Consumed before returning, inside the lock, so the
                // same code cannot succeed twice.
                $this->cache()->forget($key);

                return true;
            }

            $challenge['attempts'] = (int) $challenge['attempts'] + 1;

            if ($challenge['attempts'] >= $config['max_attempts']) {
                $this->cache()->forget($key);

                return false;
            }

            /*
             * ⚠️ Re-stored against the ORIGINAL expiry, never a fresh TTL.
             *
             * `put()` with a duration would restart the clock, so a stream of wrong
             * guesses would keep a challenge alive indefinitely — turning an attempt
             * limit into an attempt-limit-per-three-minutes and giving an attacker
             * unbounded time. The absolute timestamp is stored in the challenge for
             * exactly this.
             */
            $this->cache()->put($key, $challenge, Carbon::createFromTimestamp($challenge['expires_at']));

            return false;
        } finally {
            $lock->release();
        }
    }

    /**
     * Throw away a challenge and its cooldown.
     *
     * For an application that has finished with a flow — the person changed their
     * mind, or logged in another way — and wants the outstanding code dead.
     */
    public function forget(string $to, string $purpose): void
    {
        $number = $this->normalizer->normalize($to);

        if ($number === null) {
            return;
        }

        $this->cache()->forget($this->key('challenge', $number->e164, $purpose));
        $this->cache()->forget($this->key('cooldown', $number->e164, $purpose));
    }

    /**
     * What to do with the challenge, given what the pipeline did with the message.
     *
     * The three interesting cases and why they differ:
     *
     *   - **accepted** — a gateway has it. Keep everything.
     *   - **unknown** — nobody knows whether it arrived. ⚠️ **Keep everything.**
     *     Deleting would leave somebody holding a code this package has decided to
     *     forget, which is worse than a code that goes unused.
     *   - **failed or suppressed** — provably nothing was delivered. Destroy the
     *     challenge, and release the cooldown too: making somebody wait ninety
     *     seconds for a code that definitely never left is punishing them for the
     *     provider's failure.
     */
    private function settle($message, string $e164, string $purpose): OtpResult
    {
        return match ($message->status) {
            MessageStatus::Accepted => OtpResult::of(OtpStatus::Sent, $message),
            MessageStatus::Suppressed => $this->discard($e164, $purpose, OtpStatus::Suppressed, $message),
            MessageStatus::Failed => $this->discard($e164, $purpose, OtpStatus::Failed, $message),
            default => OtpResult::of(OtpStatus::Unknown, $message),
        };
    }

    private function discard(string $e164, string $purpose, OtpStatus $status, $message): OtpResult
    {
        $this->cache()->forget($this->key('challenge', $e164, $purpose));
        $this->cache()->forget($this->key('cooldown', $e164, $purpose));

        return OtpResult::of($status, $message);
    }

    /**
     * @param  array{length: int, expires: int, resend_after: int, max_attempts: int}  $config
     */
    private function write(string $e164, string $purpose, string $code, array $config): void
    {
        $expiresAt = Carbon::now()->addSeconds($config['expires']);

        $this->cache()->put($this->key('challenge', $e164, $purpose), [
            // ⚠️ A one-way hash, never the digits. This cache is shared
            // infrastructure - a database table or a Redis instance - and anything
            // that can read it would otherwise be able to read live codes.
            'hash' => Hash::make($code),
            'attempts' => 0,
            // Absolute, so a wrong guess can be recorded without moving the expiry.
            'expires_at' => $expiresAt->getTimestamp(),
        ], $expiresAt);
    }

    /**
     * The cache key for one challenge.
     *
     * ⚠️ **The phone number never appears in it.** Cache keys turn up in `KEYS`
     * output, in a database table anyone with read access can list, and in
     * monitoring tools — and a key containing a number would make that store an
     * enumerable list of everybody currently being sent a code. A SHA-256 of the
     * canonical number and the purpose gives a stable, opaque key.
     *
     * ⚠️ The PURPOSE is part of it, so one number can hold a login challenge and a
     * withdrawal-confirmation challenge at once without either overwriting the
     * other. Keying by number alone would make two flows silently fight.
     *
     * The canonical E.164 form is hashed, never the caller's spelling, so
     * `09121234567` and `+989121234567` reach the same challenge.
     */
    private function key(string $kind, string $e164, string $purpose): string
    {
        return sprintf('sms:otp:%s:%s', $kind, hash('sha256', $e164.'|'.$purpose));
    }

    private function cache(): Repository
    {
        return Cache::store(config('laravel-sms.otp.store') ?? config('laravel-sms.lock.store'));
    }

    /**
     * ⚠️ Validated rather than trusted, because every one of these is a security
     * parameter and a nonsensical value fails open. A length of 1 is ten possible
     * codes; an expiry of 0 or a max_attempts of 0 breaks verification outright.
     *
     * @return array{length: int, expires: int, resend_after: int, max_attempts: int}
     */
    private function config(): array
    {
        $config = [
            'length' => (int) config('laravel-sms.otp.length', 6),
            'expires' => (int) config('laravel-sms.otp.expires', 180),
            'resend_after' => (int) config('laravel-sms.otp.resend_after', 90),
            'max_attempts' => (int) config('laravel-sms.otp.max_attempts', 5),
        ];

        return match (true) {
            $config['length'] < 4 || $config['length'] > 10 => throw new SmsException(
                'laravel-sms.otp.length must be between 4 and 10 digits.',
            ),
            $config['expires'] < 1 => throw new SmsException('laravel-sms.otp.expires must be at least one second.'),
            $config['resend_after'] < 0 => throw new SmsException('laravel-sms.otp.resend_after cannot be negative.'),
            $config['max_attempts'] < 1 => throw new SmsException('laravel-sms.otp.max_attempts must be at least one.'),
            default => $config,
        };
    }
}
